CLASS ycl_aai_ddic_structure_tools DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycl_aai_ddic_structure_tools IMPLEMENTATION.
ENDCLASS.
